'use client'
import { useState, useEffect, useCallback } from 'react'
import AuthGuard from '@/components/AuthGuard'
import Sidebar from '@/components/layout/Sidebar'
import TopBar from '@/components/layout/TopBar'
import BottomNav from '@/components/layout/BottomNav'
import { useApp } from '@/context/AppContext'
import { useAttendance } from '@/hooks/useAttendance'
import { getAllPayPeriods, detailedEarningsForPeriod, PayPeriod } from '@/lib/payroll'
import { getAllPayrollRecords, savePayrollRecord } from '@/lib/firestore'
import { formatCurrency } from '@/lib/attendance'
import { PayrollRecord } from '@/types'
import { format, parseISO, isAfter, isBefore, isToday } from 'date-fns'
import {
  Banknote, ChevronDown, ChevronUp, Download, CheckCircle2,
  Clock, Calendar, TrendingUp, AlertCircle, FileText, Loader2
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { toast } from 'sonner'

// ─── Pay slip print ───────────────────────────────────────────────────────────

function printPaySlip(slip: PaySlipData, currency: string) {
  const fmt = (n: number) => `${currency}${n.toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
  const html = `<!DOCTYPE html><html><head><title>Pay Slip – ${slip.period.label}</title>
<style>
  body{font-family:sans-serif;margin:0;padding:32px;color:#111;font-size:13px;}
  .header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px;padding-bottom:16px;border-bottom:2px solid #10b981;}
  .brand{font-size:20px;font-weight:800;color:#10b981;}
  .brand span{display:block;font-size:10px;font-weight:500;color:#888;letter-spacing:2px;text-transform:uppercase;margin-top:2px;}
  .meta{text-align:right;font-size:11px;color:#555;}
  .meta strong{display:block;font-size:14px;color:#111;margin-bottom:2px;}
  h3{font-size:11px;text-transform:uppercase;letter-spacing:1.5px;color:#888;margin:20px 0 8px;}
  table{width:100%;border-collapse:collapse;}
  td{padding:7px 0;border-bottom:1px solid #f0f0f0;}
  td:last-child{text-align:right;font-weight:600;}
  .total td{border-top:2px solid #111;border-bottom:none;font-weight:800;font-size:15px;padding-top:10px;}
  .badge{display:inline-block;padding:3px 10px;border-radius:99px;font-size:10px;font-weight:700;background:#d1fae5;color:#065f46;}
  .footer{margin-top:32px;padding-top:16px;border-top:1px solid #eee;font-size:10px;color:#aaa;text-align:center;}
</style></head><body>
<div class="header">
  <div><div class="brand">ClockIn<span>Pay Slip</span></div></div>
  <div class="meta">
    <strong>${slip.employeeName}</strong>
    Period: ${slip.period.label}<br/>
    Pay Date: ${format(parseISO(slip.period.payDate), 'MMMM d, yyyy')}
    ${slip.status === 'paid' ? '<br/><span class="badge">✓ Paid</span>' : ''}
  </div>
</div>
<h3>Earnings</h3>
<table>
  <tr><td>Regular Pay (${slip.daysWorked} day${slip.daysWorked !== 1 ? 's' : ''} × ${fmt(slip.regularPay / Math.max(slip.daysWorked, 1))})</td><td>${fmt(slip.regularPay)}</td></tr>
  ${slip.otHours > 0 ? `<tr><td>Overtime Pay (${slip.otHours.toFixed(1)}h)</td><td>${fmt(slip.otPay)}</td></tr>` : ''}
  ${slip.holidayPay > 0 ? `<tr><td>Holiday Pay</td><td>${fmt(slip.holidayPay)}</td></tr>` : ''}
  <tr><td style="font-weight:700">Gross Pay</td><td style="font-weight:700">${fmt(slip.grossPay)}</td></tr>
</table>
<h3>Deductions</h3>
<table>
  <tr><td>Late Deductions (${slip.lateMinutes} min)</td><td style="color:#ef4444">-${fmt(slip.lateDeductions)}</td></tr>
  <tr><td style="font-weight:700">Total Deductions</td><td style="font-weight:700;color:#ef4444">-${fmt(slip.lateDeductions)}</td></tr>
</table>
<table style="margin-top:16px"><tr class="total"><td>NET PAY</td><td>${fmt(slip.netPay)}</td></tr></table>
<div class="footer">Generated by ClockIn · ${format(new Date(), 'MMMM d, yyyy h:mm a')}</div>
</body></html>`

  const w = window.open('', '_blank')
  if (!w) { toast.error('Please allow popups to download PDF'); return }
  w.document.write(html)
  w.document.close()
  w.focus()
  setTimeout(() => { w.print() }, 300)
}

// ─── Types ────────────────────────────────────────────────────────────────────

interface PaySlipData {
  period: PayPeriod
  employeeName: string
  status: 'pending' | 'paid' | 'in-progress'
  daysWorked: number
  totalHours: number
  otHours: number
  lateMinutes: number
  regularPay: number
  otPay: number
  holidayPay: number
  lateDeductions: number
  grossPay: number
  netPay: number
  paidDate?: string
}

// ─── Period Card ──────────────────────────────────────────────────────────────

function PeriodCard({
  slip, currency, onMarkPaid, marking,
}: {
  slip: PaySlipData
  currency: string
  onMarkPaid: () => void
  marking: boolean
}) {
  const [open, setOpen] = useState(false)
  const today = format(new Date(), 'yyyy-MM-dd')
  const isInProgress = slip.period.cutoffStart <= today && slip.period.cutoffEnd >= today
  const isFuture = slip.period.cutoffStart > today

  const statusConfig = {
    paid:        { label: 'Paid',        cls: 'bg-emerald-50 text-emerald-600 border border-emerald-200' },
    pending:     { label: 'Pending',     cls: 'bg-amber-50 text-amber-600 border border-amber-200' },
    'in-progress': { label: 'In Progress', cls: 'bg-blue-50 text-blue-600 border border-blue-200' },
  }
  const sc = statusConfig[slip.status]

  return (
    <div className={cn('bg-white rounded-2xl border shadow-sm transition-all', open ? 'border-emerald-200' : 'border-gray-100')}>
      {/* Header row */}
      <button
        onClick={() => !isFuture && setOpen((o) => !o)}
        className={cn('w-full flex items-center gap-3 px-5 py-4 text-left', isFuture ? 'cursor-default opacity-60' : 'cursor-pointer hover:bg-gray-50/50 rounded-2xl')}
      >
        <div className={cn('w-10 h-10 rounded-xl flex items-center justify-center shrink-0', slip.status === 'paid' ? 'bg-emerald-100' : isInProgress ? 'bg-blue-100' : 'bg-gray-100')}>
          {slip.status === 'paid'
            ? <CheckCircle2 className="w-5 h-5 text-emerald-600" />
            : isInProgress ? <Clock className="w-5 h-5 text-blue-500" />
            : <Banknote className="w-5 h-5 text-gray-400" />}
        </div>
        <div className="flex-1 min-w-0">
          <p className="font-bold text-gray-900 text-sm">{slip.period.label}</p>
          <p className="text-xs text-gray-400 mt-0.5">Pay date: {format(parseISO(slip.period.payDate), 'MMM d, yyyy')}</p>
        </div>
        <div className="text-right mr-3 hidden sm:block">
          <p className="font-extrabold text-gray-900">{formatCurrency(slip.netPay, currency)}</p>
          <p className="text-[10px] text-gray-400 mt-0.5">{slip.daysWorked} days worked</p>
        </div>
        <span className={cn('text-[10px] px-2.5 py-1 rounded-full font-bold shrink-0 hidden sm:inline', sc.cls)}>{sc.label}</span>
        {!isFuture && (open ? <ChevronUp className="w-4 h-4 text-gray-400 shrink-0" /> : <ChevronDown className="w-4 h-4 text-gray-400 shrink-0" />)}
      </button>

      {/* Mobile amount row */}
      <div className="sm:hidden flex items-center justify-between px-5 pb-3 -mt-1">
        <span className={cn('text-[10px] px-2.5 py-1 rounded-full font-bold', sc.cls)}>{sc.label}</span>
        <p className="font-extrabold text-gray-900">{formatCurrency(slip.netPay, currency)}</p>
      </div>

      {/* Expanded detail */}
      {open && (
        <div className="border-t border-gray-100 px-5 py-5 space-y-5">
          {/* Stats row */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {[
              { label: 'Days Worked', value: `${slip.daysWorked}`, sub: 'this period', color: 'text-indigo-600', bg: 'bg-indigo-50' },
              { label: 'Hours Worked', value: `${slip.totalHours.toFixed(1)}h`, sub: 'total logged', color: 'text-blue-600', bg: 'bg-blue-50' },
              { label: 'Overtime', value: `${slip.otHours.toFixed(1)}h`, sub: 'extra hours', color: 'text-orange-600', bg: 'bg-orange-50' },
              { label: 'Late', value: `${slip.lateMinutes}m`, sub: 'total late', color: 'text-amber-600', bg: 'bg-amber-50' },
            ].map((s) => (
              <div key={s.label} className={cn('rounded-xl p-3.5', s.bg)}>
                <p className={cn('text-xl font-extrabold', s.color)}>{s.value}</p>
                <p className="text-[11px] font-semibold text-gray-600 mt-0.5">{s.label}</p>
                <p className="text-[10px] text-gray-400">{s.sub}</p>
              </div>
            ))}
          </div>

          {/* Earnings breakdown */}
          <div className="bg-gray-50 rounded-xl p-4 space-y-2.5">
            <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-3">Earnings Breakdown</p>
            <div className="space-y-2">
              {[
                { label: `Regular Pay (${slip.daysWorked} days)`, value: slip.regularPay, color: 'text-gray-900' },
                ...(slip.otHours > 0 ? [{ label: `Overtime Pay (${slip.otHours.toFixed(1)}h)`, value: slip.otPay, color: 'text-orange-600' }] : []),
                ...(slip.holidayPay > 0 ? [{ label: 'Holiday Pay', value: slip.holidayPay, color: 'text-purple-600' }] : []),
              ].map((row) => (
                <div key={row.label} className="flex justify-between items-center">
                  <span className="text-sm text-gray-600">{row.label}</span>
                  <span className={cn('text-sm font-bold', row.color)}>{formatCurrency(row.value, currency)}</span>
                </div>
              ))}
              <div className="flex justify-between items-center pt-2 border-t border-gray-200">
                <span className="text-sm font-bold text-gray-800">Gross Pay</span>
                <span className="text-sm font-extrabold text-gray-900">{formatCurrency(slip.grossPay, currency)}</span>
              </div>
            </div>
            {slip.lateDeductions > 0 && (
              <div className="flex justify-between items-center pt-2 border-t border-dashed border-gray-200">
                <span className="text-sm text-red-500">Late Deduction ({slip.lateMinutes} min)</span>
                <span className="text-sm font-bold text-red-500">-{formatCurrency(slip.lateDeductions, currency)}</span>
              </div>
            )}
            <div className="flex justify-between items-center pt-3 border-t-2 border-gray-300">
              <span className="font-extrabold text-gray-900">Net Pay</span>
              <span className="text-lg font-extrabold text-emerald-600">{formatCurrency(slip.netPay, currency)}</span>
            </div>
          </div>

          {/* Actions */}
          <div className="flex items-center gap-3 flex-wrap">
            <button
              onClick={() => printPaySlip(slip, currency)}
              className="flex items-center gap-2 px-4 py-2.5 bg-gray-800 hover:bg-gray-900 text-white text-sm font-bold rounded-xl transition-colors cursor-pointer"
            >
              <Download className="w-4 h-4" />
              Download PDF
            </button>
            {slip.status !== 'paid' && slip.status !== 'in-progress' && (
              <button
                onClick={onMarkPaid}
                disabled={marking}
                className="flex items-center gap-2 px-4 py-2.5 bg-emerald-500 hover:bg-emerald-600 text-white text-sm font-bold rounded-xl transition-colors cursor-pointer disabled:opacity-60"
              >
                {marking ? <Loader2 className="w-4 h-4 animate-spin" /> : <CheckCircle2 className="w-4 h-4" />}
                Mark as Paid
              </button>
            )}
            {slip.status === 'paid' && slip.paidDate && (
              <p className="text-xs text-emerald-600 font-semibold">
                Paid on {format(parseISO(slip.paidDate), 'MMM d, yyyy')}
              </p>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

// ─── Main page ────────────────────────────────────────────────────────────────

function PayrollPage() {
  const { user, settings } = useApp()
  const { records, loading: recLoading } = useAttendance(user?.uid ?? null, settings)
  const [payrollRecords, setPayrollRecords] = useState<PayrollRecord[]>([])
  const [loading, setLoading] = useState(true)
  const [marking, setMarking] = useState<string | null>(null)

  useEffect(() => {
    if (!user?.uid) return
    getAllPayrollRecords(user.uid).then((recs) => {
      setPayrollRecords(recs)
      setLoading(false)
    })
  }, [user?.uid])

  const handleMarkPaid = useCallback(async (slip: PaySlipData) => {
    if (!user?.uid) return
    setMarking(slip.period.cutoffStart)
    const rec: PayrollRecord = {
      id: `${slip.period.cutoffStart}_${slip.period.cutoffEnd}`,
      periodStart: slip.period.cutoffStart,
      periodEnd: slip.period.cutoffEnd,
      payDate: slip.period.payDate,
      periodLabel: slip.period.label,
      status: 'paid',
      paidDate: format(new Date(), 'yyyy-MM-dd'),
      grossPay: slip.grossPay,
      regularPay: slip.regularPay,
      otPay: slip.otPay,
      holidayPay: slip.holidayPay,
      lateDeductions: slip.lateDeductions,
      netPay: slip.netPay,
      daysWorked: slip.daysWorked,
      totalHours: slip.totalHours,
      otHours: slip.otHours,
      lateMinutes: slip.lateMinutes,
      createdAt: new Date().toISOString(),
    }
    await savePayrollRecord(user.uid, rec)
    setPayrollRecords((prev) => [...prev.filter((r) => r.id !== rec.id), rec])
    setMarking(null)
    toast.success('Marked as paid!')
  }, [user?.uid])

  if (!settings) return null

  const today = format(new Date(), 'yyyy-MM-dd')
  const currency = settings.currency ?? '₱'

  // Generate all periods from earliest record (or 3 months back) to end of next month
  const earliest = records.length > 0
    ? parseISO(records[records.length - 1].date)
    : new Date(new Date().getFullYear(), new Date().getMonth() - 2, 1)
  const future = new Date(new Date().getFullYear(), new Date().getMonth() + 1, 28)
  const periods = getAllPayPeriods(settings, earliest, future)

  // Build pay slips
  const slips: PaySlipData[] = periods.map((period) => {
    const saved = payrollRecords.find((r) => r.id === `${period.cutoffStart}_${period.cutoffEnd}`)
    const { daysWorked, totalHours, otHours, lateMinutes, lateDeductions, grossPay, recs } =
      detailedEarningsForPeriod(records, period)

    const regularPay = recs.reduce((s, r) => {
      const ot = r.otHours > 0 ? (r.dailyEarnings * (r.otHours / Math.max(r.hoursWorked, 0.01))) : 0
      return s + (r.dailyEarnings || 0) - ot
    }, 0)
    const otPay = grossPay - regularPay
    const holidayPay = 0 // could be derived if needed
    const netPay = Math.max(0, grossPay - lateDeductions)

    const isInProgress = period.cutoffStart <= today && period.cutoffEnd >= today
    const isFuture = period.cutoffStart > today
    const status: PaySlipData['status'] = saved?.status === 'paid' ? 'paid'
      : isInProgress ? 'in-progress'
      : isFuture ? 'pending'
      : 'pending'

    return {
      period,
      employeeName: settings.name || 'Employee',
      status,
      daysWorked,
      totalHours,
      otHours,
      lateMinutes,
      regularPay: Math.max(0, regularPay),
      otPay: Math.max(0, otPay),
      holidayPay,
      lateDeductions,
      grossPay,
      netPay,
      paidDate: saved?.paidDate,
    }
  }).reverse() // newest first

  // Group by year
  type Group = { year: number; slips: PaySlipData[] }
  const grouped: Group[] = []
  for (const slip of slips) {
    const y = parseISO(slip.period.cutoffStart).getFullYear()
    let g = grouped.find((gg) => gg.year === y)
    if (!g) { g = { year: y, slips: [] }; grouped.push(g) }
    g.slips.push(slip)
  }

  const totalPaid = slips.filter((s) => s.status === 'paid').reduce((sum, s) => sum + s.netPay, 0)
  const totalPending = slips.filter((s) => s.status === 'pending').reduce((sum, s) => sum + s.netPay, 0)
  const inProgress = slips.find((s) => s.status === 'in-progress')

  return (
    <div className="flex h-screen overflow-hidden bg-gray-50">
      <Sidebar />
      <div className="flex-1 flex flex-col overflow-hidden min-w-0">
        <TopBar title="Payroll" />
        <main className="flex-1 overflow-y-auto p-4 lg:p-6 space-y-5 pb-24 lg:pb-6">

          {/* Header */}
          <div>
            <h2 className="text-xl font-extrabold text-gray-900">Payroll & Pay Slips</h2>
            <p className="text-sm text-gray-400 mt-0.5">Track your pay periods and download pay slips</p>
          </div>

          {/* Summary cards */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-emerald-100 rounded-xl flex items-center justify-center">
                  <CheckCircle2 className="w-5 h-5 text-emerald-600" />
                </div>
                <div>
                  <p className="text-xs font-semibold text-gray-400">Total Received</p>
                  <p className="text-xl font-extrabold text-gray-900">{formatCurrency(totalPaid, currency)}</p>
                </div>
              </div>
            </div>
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-blue-100 rounded-xl flex items-center justify-center">
                  <Clock className="w-5 h-5 text-blue-500" />
                </div>
                <div>
                  <p className="text-xs font-semibold text-gray-400">Current Period</p>
                  <p className="text-xl font-extrabold text-gray-900">
                    {inProgress ? formatCurrency(inProgress.netPay, currency) : '—'}
                  </p>
                </div>
              </div>
            </div>
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-amber-100 rounded-xl flex items-center justify-center">
                  <Banknote className="w-5 h-5 text-amber-500" />
                </div>
                <div>
                  <p className="text-xs font-semibold text-gray-400">Unpaid Periods</p>
                  <p className="text-xl font-extrabold text-gray-900">{formatCurrency(totalPending, currency)}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Period list */}
          {(loading || recLoading) ? (
            <div className="space-y-3">
              {[...Array(4)].map((_, i) => (
                <div key={i} className="bg-white rounded-2xl border border-gray-100 h-20 animate-pulse" />
              ))}
            </div>
          ) : grouped.length === 0 ? (
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm py-20 flex flex-col items-center gap-3">
              <div className="w-14 h-14 bg-gray-100 rounded-2xl flex items-center justify-center">
                <FileText className="w-6 h-6 text-gray-400" />
              </div>
              <p className="font-bold text-gray-600">No pay periods yet</p>
              <p className="text-sm text-gray-400">Start clocking in to generate pay slip records</p>
            </div>
          ) : (
            grouped.map(({ year, slips: yearSlips }) => (
              <div key={year} className="space-y-3">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-widest px-1">{year}</p>
                {yearSlips.map((slip) => (
                  <PeriodCard
                    key={slip.period.cutoffStart}
                    slip={slip}
                    currency={currency}
                    marking={marking === slip.period.cutoffStart}
                    onMarkPaid={() => handleMarkPaid(slip)}
                  />
                ))}
              </div>
            ))
          )}
        </main>
      </div>
      <BottomNav />
    </div>
  )
}

export default function Payroll() {
  return <AuthGuard><PayrollPage /></AuthGuard>
}
